#!/usr/bin/env python3
import json
import keyword
import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "obdb-src"
OUT_FILE = ROOT / "obdb" / "commands.py"


def py_ident(name):
    s = re.sub(r"[^0-9A-Za-z_]", "_", str(name))
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "unnamed"
    if s[0].isdigit():
        s = "_" + s
    if keyword.iskeyword(s):
        s = s + "_"
    return s


def signal_py_name(signal, index):
    for key in ("id", "name", "path"):
        value = signal.get(key)
        if value:
            return py_ident(value)
    return f"signal_{index}"


def command_desc(signal, entry):
    parts = []
    for key in ("name", "id", "path"):
        value = signal.get(key)
        if value:
            parts.append(str(value))
            break
    hdr = entry.get("hdr")
    if hdr:
        parts.append(f"hdr={hdr}")
    return " | ".join(parts) if parts else "OBDb signal"


def clean_hex(value):
    return "".join(ch for ch in str(value) if ch in "0123456789abcdefABCDEF").upper()


def parse_cmd(cmd_map):
    if not isinstance(cmd_map, dict) or len(cmd_map) != 1:
        return None
    service_hex, pid_hex = next(iter(cmd_map.items()))
    service_hex = clean_hex(service_hex)
    pid_hex = clean_hex(pid_hex)
    if not service_hex or not pid_hex:
        return None
    return {
        "service_hex": service_hex,
        "pid_hex": pid_hex,
        "command_hex": service_hex + pid_hex,
        "response_prefix_hex": f"{int(service_hex, 16) + 0x40:02X}{pid_hex}",
    }


def expected_bytes(signals):
    bit_end = 0
    for signal in signals:
        fmt = signal.get("fmt", {})
        bix = int(fmt.get("bix", 0))
        bitlen = int(fmt.get("len", 0))
        if bix + bitlen > bit_end:
            bit_end = bix + bitlen
    return math.ceil(bit_end / 8)


def load_sources():
    items = []
    for source_dir in sorted(SRC_DIR.iterdir()):
        if not source_dir.is_dir():
            continue
        signalset = source_dir / "signalsets" / "v3" / "default.json"
        if not signalset.exists():
            continue
        data = json.loads(signalset.read_text(encoding="utf-8"))
        items.append((source_dir.name, data))
    return items


def emit_header():
    return '''"""
Auto-generated by obdb-src/generate.py
Do not edit manually.
"""

from obd import OBDCommand


class _Namespace:
    pass


def _bytes_to_int(data):
    value = 0
    for b in data:
        value = (value << 8) | int(b)
    return value


def _twos_complement(value, bits):
    if bits <= 0:
        return value
    sign_bit = 1 << (bits - 1)
    if value & sign_bit:
        return value - (1 << bits)
    return value


def _extract_bits_be(payload, bix, bitlen, signed=False):
    if bitlen <= 0:
        return 0
    total_bits = len(payload) * 8
    if bix < 0 or total_bits < bix + bitlen:
        raise ValueError(f"bit range out of payload: bix={bix} len={bitlen} total={total_bits}")
    raw = _bytes_to_int(payload)
    shift = total_bits - (bix + bitlen)
    mask = (1 << bitlen) - 1
    value = (raw >> shift) & mask
    if signed:
        value = _twos_complement(value, bitlen)
    return value


def _strip_response_prefix(data, response_prefix):
    if len(data) >= len(response_prefix) and bytes(data[:len(response_prefix)]) == response_prefix:
        return bytes(data[len(response_prefix):])
    if len(data) >= 1 and response_prefix and data[0] == response_prefix[0]:
        return bytes(data[1:])
    return bytes(data)


def _make_decoder(response_prefix, bix, bitlen, mul, add, signed):
    def decoder(messages):
        if not messages:
            return None
        data = bytes(messages[0].data)
        payload = _strip_response_prefix(data, response_prefix)
        value = _extract_bits_be(payload, bix, bitlen, signed=signed)
        value = value * mul + add
        return value
    return decoder


_ORIGINAL_SOURCE_NAMES = {}
_ORIGINAL_COMMAND_NAMES = {}
'''

def emit_header_arg(hdr):
    if not hdr:
        return ""
    return f', header=b"{hdr}"'

def emit_source_block(source_name, data):
    source_ident = py_ident(source_name)
    lines = []
    lines.append(f"{source_ident} = _Namespace()")
    lines.append(f'_ORIGINAL_SOURCE_NAMES["{source_ident}"] = "{source_name}"')
    lines.append(f'_ORIGINAL_COMMAND_NAMES["{source_ident}"] = {{}}')

    used_names = set()
    for entry in data.get("commands", []):
        cmd_info = parse_cmd(entry.get("cmd"))
        signals = entry.get("signals", [])
        if not cmd_info or not signals:
            continue

        hdr = entry.get("hdr")
        hdr = clean_hex(hdr) if hdr else None
        bytes_expected = expected_bytes(signals)

        for index, signal in enumerate(signals):
            fmt = signal.get("fmt", {})
            bitlen = int(fmt.get("len", 0))
            if bitlen <= 0:
                continue

            name_original = signal.get("id") or signal.get("name") or signal.get("path") or f"signal_{index}"
            name_ident = signal_py_name(signal, index)

            if name_ident in used_names:
                suffix = 2
                while f"{name_ident}_{suffix}" in used_names:
                    suffix += 1
                name_ident = f"{name_ident}_{suffix}"
            used_names.add(name_ident)

            bix = int(fmt.get("bix", 0))
            mul = fmt.get("mul", 1)
            add = fmt.get("add", 0)
            signed = "True" if bool(fmt.get("signed", False)) else "False"
            desc = command_desc(signal, entry).replace("\\", "\\\\").replace('"', '\\"')

            lines.append(
                f'{source_ident}.{name_ident} = OBDCommand('
                f'"{name_ident}", '
                f'"{desc}", '
                f'b"{cmd_info["command_hex"]}", '
                f'{bytes_expected + len(bytes.fromhex(cmd_info["command_hex"]))}, '
                f'_make_decoder(bytes.fromhex("{cmd_info["response_prefix_hex"]}"), {bix}, {bitlen}, {repr(mul)}, {repr(add)}, {signed})'
                f'{emit_header_arg(hdr)})'
            )
            lines.append(f'_ORIGINAL_COMMAND_NAMES["{source_ident}"]["{name_ident}"] = "{name_original}"')

    lines.append("")
    return "\n".join(lines)


def emit_footer(source_names):
    exported = [py_ident(name) for name in source_names]
    exported.append("_ORIGINAL_SOURCE_NAMES")
    exported.append("_ORIGINAL_COMMAND_NAMES")
    return "__all__ = [\n    " + ",\n    ".join(repr(x) for x in exported) + "\n]\n"


def main():
    sources = load_sources()
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    parts = [emit_header()]
    for source_name, data in sources:
        parts.append(emit_source_block(source_name, data))
    parts.append(emit_footer([name for name, _ in sources]))

    OUT_FILE.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()